# Generated by Django 4.0.5 on 2022-06-26 13:26

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.BaseUserManager()),
            ],
        ),
    ]
