# Generated by Django 4.0.5 on 2022-06-27 19:42

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_otp_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otpCode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otpExpire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{10,11}$'), core.models.User.phone_validator]),
        ),
    ]
