# Generated by Django 4.0.5 on 2022-06-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_profilestud_is_verified_alter_profilementor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestud',
            name='major',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
