# Generated by Django 4.0.5 on 2022-06-13 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0004_profilestud_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedProjects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='verificationdoc',
            name='document',
            field=models.FileField(upload_to='web/uploads'),
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.requestedprojects')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.project')),
            ],
        ),
    ]
