# Generated by Django 4.0.5 on 2022-06-13 12:56

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_requestedprojects_alter_verificationdoc_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#ffff', image_field=None, max_length=18, samples=None),
        ),
    ]
