# Generated by Django 4.0.5 on 2022-06-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_tag_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilementor',
            name='tag',
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(to='web.tag'),
        ),
    ]
