# Generated by Django 4.0.5 on 2022-06-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_profilementor_tag_project_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(related_name='projects', to='web.tag'),
        ),
    ]
