# Generated by Django 4.0.5 on 2022-06-14 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='web.project'),
        ),
    ]
