# Generated by Django 4.0.5 on 2022-06-18 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0012_alter_requestitem_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='p', max_length=5),
        ),
        migrations.AlterField(
            model_name='requestedprojects',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='requested_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='web.requestedprojects'),
        ),
    ]
