# Generated by Django 4.0.5 on 2022-06-19 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0014_approvedrequest_approveditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approveditem',
            name='passed',
        ),
        migrations.AddField(
            model_name='approveditem',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('C', 'Canceled'), ('P', 'Passed')], default='A', max_length=5),
        ),
        migrations.AlterField(
            model_name='approvedrequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
