# Generated by Django 4.0.5 on 2022-06-19 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_approveditem_passed_approveditem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approveditem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='web.approvedrequest'),
        ),
    ]
