# Generated by Django 4.0.5 on 2022-06-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_verificationdoc_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestud',
            name='resume',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
