# Generated by Django 4.0.5 on 2022-06-24 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0022_alter_verificationdoc_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdoc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='VerDocs', to=settings.AUTH_USER_MODEL),
        ),
    ]
