# Generated by Django 4.0.5 on 2022-06-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_verificationdoc_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdoc',
            name='document',
            field=models.FileField(upload_to='web/uploads'),
        ),
    ]
