# Generated by Django 4.0.5 on 2022-06-24 12:24

from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_verificationdoc_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdoc',
            name='document',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='', verbose_name='File'),
        ),
    ]
