# Generated by Django 4.0.5 on 2022-06-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_alter_profilementor_user_alter_profilestud_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestud',
            name='major',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='profilestud',
            name='resume',
            field=models.TextField(blank=True),
        ),
    ]
