# Generated by Django 4.0.5 on 2022-06-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_remove_profilestud_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admissionNo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
