# Generated by Django 4.0.5 on 2022-06-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_alter_project_admissionno'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='message_from_mentor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
