# Generated by Django 4.0.5 on 2022-06-30 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_approvedrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('C', 'Canceled'), ('P', 'Passed')], default='A', max_length=5)),
                ('message_from_mentor', models.TextField(blank=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='web.approvedrequest')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.project')),
            ],
        ),
    ]
