# Generated by Django 4.0.5 on 2022-06-30 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0035_alter_approveditem_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedrequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approved_projects_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='approveditem',
            unique_together={('parent', 'project')},
        ),
    ]
