# Generated by Django 4.0.5 on 2022-07-01 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_alter_approvedrequest_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approveditem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='web.approvedrequest', verbose_name='user_cart'),
        ),
        migrations.AlterField(
            model_name='approveditem',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('R', 'REJECTED'), ('P', 'Passed')], default='A', max_length=5),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web.requestedprojects'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='web.project'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('A', 'Approve'), ('R', 'Reject')], default='p', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='requestitem',
            unique_together={('parent', 'project')},
        ),
    ]
