# Generated by Django 4.0.5 on 2022-06-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_alter_approvedrequest_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approveditem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web.approvedrequest'),
        ),
        migrations.AlterField(
            model_name='approveditem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_projects', to='web.project'),
        ),
    ]
