# Generated by Django 4.0.5 on 2022-07-03 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_alter_approveditem_parent_alter_approveditem_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageForAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='approvedrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='requestitem',
            name='message_from_mentor',
        ),
        migrations.AddField(
            model_name='requestitem',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='web.requestedprojects'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='web.project'),
        ),
        migrations.DeleteModel(
            name='ApprovedItem',
        ),
        migrations.DeleteModel(
            name='ApprovedRequest',
        ),
        migrations.AddField(
            model_name='messageforadmission',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='web.requestitem'),
        ),
    ]
