# Generated by Django 4.0.5 on 2022-07-01 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_alter_approveditem_parent_alter_approveditem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='web.requestedprojects'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='web.project'),
        ),
    ]
