# Generated by Django 4.0.5 on 2022-07-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_alter_approveditem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approveditem',
            unique_together={('parent', 'project')},
        ),
    ]
