# Generated by Django 4.0.5 on 2022-07-01 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_alter_approveditem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approveditem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='web.approvedrequest', verbose_name='user_cart'),
        ),
        migrations.AlterField(
            model_name='approveditem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_projects', to='web.project'),
        ),
    ]
