# Generated by Django 4.0.5 on 2022-07-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_mentormessageforadmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
