# Generated by Django 4.0.5 on 2022-07-01 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_alter_approveditem_parent_alter_approveditem_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approveditem',
            name='message_from_mentor',
        ),
        migrations.RemoveField(
            model_name='requestitem',
            name='message_from_mentor',
        ),
        migrations.CreateModel(
            name='MessageForAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='web.approveditem')),
            ],
        ),
    ]
