# Generated by Django 4.0.6 on 2022-07-06 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_alter_project_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='approved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestitem',
            name='passed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
