# Generated by Django 4.0.5 on 2022-07-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_remove_approveditem_message_from_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
